
name: Update publications
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs once a day
   - cron:  '0 9 1 * *'
jobs:
  notebooks:
    name: "Scrape and update publications"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.0

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          brew install tectonic
          
      - name: Scrape publications
        env:
          ADS_DEV_KEY: ${{secrets.ADS_SECRET}}
        run: |
          cd scripts
          python scrape_ads.py
          
      - name: Format publications
        run: |
          cd scripts
          python format_pubs.py

      - name: Generate PDF
        run: | 
          tectonic resume.tex --print
          
      - run: git pull
          
      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Scrape and update publications
